### ISSUE TITLE
1 Dashboard

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#1]
# User Story 1 "Dashboard"

## Value proposition
As a user
I want to have a dashboard
to be able to navigate between pages

![Image](https://user-images.githubusercontent.com/123933016/227456821-030123f7-f5e6-45dc-8546-84bbaa50b9e3.png)

## Acceptance Criteria: 
- [ ] the title "CoPlan" is displayed at the top
- [ ] there is a button link that leads to the to-do-board
- [ ] the text "To Do Board" is displayed underneath

## Tasks:
- [ ] create front page
- [ ] create a button link that leads to the to do board

**Comment by liebeckm** [comment]
LGTM ⭐️ !

**Comment by PReichetanz** [comment]
Hi

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## General
- The idea of a Dashboard is great, but I would argue that it should not be the first story: it's to big.
- **Don't delete the story: keep it, postpone it and adapt the story as soon as you can implement a dashboard** (because you already have a working list + form to add new todos).
- Alternative: start with the form (or simply with a hardcoded list of todos, if you'd like). If you choose the form, you can use the right part of your wireframe and adapt it.
- You can also keep parts of the ACs and Tasks for the form user story.

**Comment by supernova-97** [comment]
@PReichetanz thanks for the feedback. One question though: What do you mean by "it's too big"?
Too big for one story or too big as a component? Because for now it's just a page with a button. 
Since I'll need the dashboard later for other features I thought it's good to already have it.

**Comment by PReichetanz** [comment]
Too big for one story and for the first story: if it is the first one, you do not have a page to redirect the user to.

And: "Since I'll need the dashboard later for other features I thought it's good to already have it." - I completely understand this thought, but it's exactly what we need to avoid: we don't build for the future, we build for right now. And right now, your user needs to see todos or add new ones, not a dashboard without any usage ;)

**Comment by supernova-97** [comment]
@PReichetanz got it! Thanks :)

**Comment by dennisbuchwald** [comment]
Hey looks great and is in my opinion also feasible, but more tasks may not be more! 😁

**Comment by PReichetanz** [comment]
Nice rework!

Two minor things to consider:
- Why do you "create an array with objects with example to-dos"? You don't display them in your description (I would think they should already be visible in the left screen?) and if you have a form, you don't need dummy data for this step.
- I'm not sure why do you create a "to-do" page for this story: If you do, what is displayed under the root path `/`? Instead, you can simply display this form + list in `pages/index.js` and move it later if necessary.

**Comment by supernova-97** [comment]
@PReichetanz I forgot to delete those points when I updated the story. Updated again
