### ISSUE TITLE
to-do board

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#1]
# To-Do Board

## Value proposition
As a user
I want to be able to create a to-do list
to be able to have a good overview over my tasks

## Description

![Image](https://user-images.githubusercontent.com/123933016/228176161-dc549bd0-3abc-4af5-888d-2fd3ffc289c2.png)

## Acceptance Criteria: 
- [x] there is an input field to type in to-dos
- [x] there is a submit button
- [x] the added to-dos will show up in a list
- [x]  there is a delete button
- [x] the list is scrollable

## Tasks:
- [x] create a heading, not fixed
- [x] create a form with an input field and a submit button
- [x] create a List component which renders the to-dos
- [x] create delete button

**Comment by supernova-97** [comment]
done
