### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#10]
# Countdown

## Value proposition
As a user
I want to be able to see a countdown 
to be able to know how many days are left until the trip

## Description
![Image](https://user-images.githubusercontent.com/123933016/227605455-535f48c2-25eb-4f07-ab26-3b4d06d59091.png)

## Acceptance Criteria: 

- [ ] the countdown should be visible on the dashboard
- [ ] it shows how many days are left
- [ ] xx days left until *trip name*

## Tasks:
- [ ] write a function that calculates the days left
- [ ] get the date data from the "new trip" form
- [ ] get the trip name from the "new trip" form
