### ISSUE TITLE
re-assign todos

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#13]
# Re-assign

## Value proposition
As a user who is planning the trip
I want to re-assign todos
to be able to give a todo to someone else

## Description

![Image](https://user-images.githubusercontent.com/123933016/230057614-1a17e050-ca99-4ab2-a315-5c579bee6625.png)

## Acceptance Criteria: 

- [ ] there is an edit button next to the todo
- [ ] clicking it will open a little window
- [ ] in that window you are able to choose another person
- [ ] after clicking on the person, the todo will be display in 
 that persons section

## Tasks:
- [ ] create an edit button
- [ ] create pop-up window

**Comment by FrankSiyli** [comment]
Nice idea 👍 LGTM
