### ISSUE TITLE
Front Page

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#14]
# Front Page

## Value proposition
As a user
I want to have a button to add a new trip when i first start the app
to be able to have a good user flow

## Description

![Image](https://user-images.githubusercontent.com/123933016/230332308-165d48b5-f738-4058-af28-c3d213686355.png)

## Acceptance Criteria: 

- [x] only the add new trip button will be displayed
- [x] after filling out the form, only the to-do-board will be displayed

## Tasks:
- [x] add conditional rendering to display either new trip button or to do board button
- [x] based on whether the data is there or not
