### ISSUE TITLE
Detailed page

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#15]
# Detailed Page

## Value proposition
As a user
I want to have a detailed page of the trip data
to be able to have a nice overview over important data regarding the trip

## Description

![Image](https://user-images.githubusercontent.com/123933016/230338866-2f9bb476-e97e-49a6-97e8-d098d329afbb.png)

## Acceptance Criteria: 

- [x] the data from the "new-trip" form will be displayed in following format:
Trip name:
Date:
Destination:
Friends:

## Tasks:
- [x] get the date from the form
- [x] display that data in the correct format

**Comment by alexWaligorski** [comment]
What a simple, yet important feature!
I have only tiny suggestions to make it clearer to the reviewers: 
* Be a bit more specific in your Value proposition e.g. I want to have a detailed page of XYZ.. to have a nice overview of XYZ
* and in the tasks: Information from which form?

Hope this helps!

**Comment by supernova-97** [comment]
@alexWaligorski thanks for the feedback!
Could you check again if the value proposition is clearer now?
I also clarified that it's the data coming from the new trip form

**Comment by alexWaligorski** [comment]
Much clearer imho
