### ISSUE TITLE
Journal

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#19]
# Journal

## Value proposition
As a user 
I want to have a journal
to be able to document the trip

## Description

![Image](https://user-images.githubusercontent.com/123933016/231447299-54b8e421-2fcb-4d0f-93cc-53135078dee0.png)

## Acceptance Criteria: 

- [x] there is a "Journal" button on the front page
- [x] clicking it will lead to the journals
- [x] if empty, "Time to create one!" will be displayed
- [x] there is a "new journal" button
- [x] click will lead to a form with input fields:
- [x] Name, Destination, Description
- [x] in the form, there is a "back to Journals" button
- [x] clicking next will lead to detailed page
- [x] there is a "back to dashboard" button

## Tasks:
- [x] create new page Journal.js
- [x] existing journals will be displayed, else "Create one" will be displayed
- [x] create form and save input in state on submit
- [x] use data from state to display info on the detailed page
- [x] create dynamic routing to access the different journals

**Comment by abieber1408** [comment]
LGMT!🗺
 I only  miss the Back to Dashboard button as a Criteria and as a Task, and also the New Trip Button. (Maybe it comes from earlier US's).
I think these looks so great, I could use your app for my own.

**Comment by supernova-97** [comment]
@abieber1408 Thank you! I added the button to the criteria. :)
