### ISSUE TITLE
checking to-dos

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#2]
# To-Do Board

## Value proposition
As a user
I want to be able to mark to-dos as done
to be able to see what's already been done 

## Description

![Image](https://user-images.githubusercontent.com/123933016/228176466-bae0bcde-68b4-4368-be82-42f3bc2d1c1e.png)

## Acceptance Criteria: 
- [x] checked to-dos will be grey and crossed out
- [x] unchecking to-do will bring it back to default state

## Tasks:
- [x] create styling for checked to-dos
- [x] create toggle function for to-do state
