### ISSUE TITLE
Journal entry

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#20]
# Journal entry

## Value proposition
As a user 
I want to upload pics to the journal
to be able to save them as memories

## Description

![Image](https://user-images.githubusercontent.com/123933016/233350398-fdab77b0-86ac-4ff8-8f28-74b26d66502f.png)

## Acceptance Criteria: 

- [x] a form to add highlights is displayed in the journals
- [x] input fields are required
- [x] submitted highlights will be displayed in the journal
- [x] highlights will be a card containing the image and the text

## Tasks:
- [x] create form for highlights

**Comment by abieber1408** [comment]
Great. !!!🤳
I would split these tree screens.
Your second screen must have an add button, and an input screen.
These tasks are not so simply. 
But I think you master this.

**Comment by supernova-97** [comment]
@abieber1408 I think I didn't describe it well. The first and third screen are the front page of the entry and the second screen is where you upload pictures that will be shown on the front page
