### ISSUE TITLE
editing todos

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#23]
# edit todos

## Value proposition
As a user
I want to edit todos
to be able to change them without deleting it

## Description

![Image](https://user-images.githubusercontent.com/123933016/233383905-5503da98-6115-49eb-a536-bd1c1dda1e8f.png)

## Acceptance Criteria: 

- [x] there is an edit button next to the todo
- [x] clicking it will give the option to put in something new
- [x] after clicking it, the button turns into save button
- [x] clicking the save button will save the changes

## Tasks:
- [x] create states for editing
- [x] create function to handle the new input
- [x] conditional rendering to switch between editing mode and viewing mode
