### ISSUE TITLE
"Planning a new trip"

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#3]
# Planning a new trip

## Value proposition
As a user
I want to be able to create a new trip
to be able to plan trips

## Description

![Image](https://user-images.githubusercontent.com/123933016/228211518-b3c59b5b-3466-47d6-bce9-25a8ebd94d76.png)

## Acceptance Criteria: 

- [x] a dashboard that will contain a button linked to the to-do board and a button linked to "new trip"
- [x] title "Plan your next trip" is shown at the top
- [x] multiple input fields to enter data about trip (all required), if not complete =alert, divided into two steps
- [x] date will open a date picker
- [x] submit button at the bottom to create trip
- [x] to-dos created in "what do we need" input will be displayed below
- [x] after submit, user will be redirected to dashboard
- [x] "back to dashboard" button

## Tasks:
- [x] create new page "Dashboard" (pages/index.js)
- [x] create new page "New Trip" (pages/new_trip/index.js)
- [x] move to-do index file into new folder (pages/to-do/index.js
- [x] in "Dashboard":
- [x] create button linked to to-do-board and button linked to "new trip"
- [x] in "New Trip":
- [x] create input fields for: name, where, when, who & what (required, if not = error)
- [x] create the submit button that saves the data
- [x] "back to dashboard" button

**Comment by alinawinter** [comment]
Looks very well thought through from beginning to end :-) An idea would be to include tests to check, whether the form works.

**Comment by PReichetanz** [comment]
Nice work, Felix!

Just one thing: the scribble of the input fields do not show where the labels will be displayed. Please adapt your wireframe to show them as well.

**Comment by supernova-97** [comment]
@PReichetanz I added the labels. Looks good?

**Comment by supernova-97** [comment]
@alinawinter I was hoping to avoid testing but I guess there's no way around it hahah

**Comment by alexWaligorski** [comment]
Hi Felix, thumbs up on this story! It's getting exciting with the features. I really want to plan my post-bootcamp vacation using your app, so hurry up ;)

I have some suggestions for you to consider:
new_trip: 
- Which fields are required? Which are optional?
- Consider using a datepicker (input type=date) for the date. Now it looks like a textinput
- What happens when a new trip is created but certain data was not given e.g. date? Maybe an error message?
- What happens when the trip was successfully created? Will the user be automatically redirectd to the dashboard?

dashboard:
- What appears on the dashboard when a new trip was created? Only the todos are shown or the whole trip? Is this a to-do-dashboard or a trip overview? 🤔
- what is the yellow rectangle above the to do board heading? if it has no functionality, consider removing it for now.

buttons:
- consider adding text to the buttons. users might not know intuitively which functionalities to expect when only icons or symbols are used. From my experience the most accessible way is to have an icon and a text beneath or next to it.

Really hope this helps!
Have a wonderful weekend.

**Comment by supernova-97** [comment]
@alexWaligorski thanks for the great feedback! I haven't thought about those details but they are very important for sure. I'll make sure to implement your suggestions 🙌🏻

**Comment by PReichetanz** [comment]
Hi Felix,

nice work! I would like to elaborate on Alex' question: what is the usage of the dashboard for now? Is anything displayed after I've submitted the form?

If not, it would be enough (for now) to add a button on the to-do-page "Add a new trip" and when clicked, a form is shown. It seems to me that the dashboard does not really have value and is rather a placeholder for later development. What do you think?

**Comment by supernova-97** [comment]
@PReichetanz Morning! In the next step I'll add a countdown to the trip that is shown on the dashboard. From there all the functions will be available. I wanted to implement it now so I don't have to move too much stuff at a later point.
Hope that makes sense.
