### ISSUE TITLE
assigning to-dos

### ISSUE THREAD

**Issue by supernova-97** [supernova-97/Capstone-Project#8]
# assigning to-dos

## Value proposition
As a user
I want to  assign to-dos to friends
to be able to have a better overview over who is doing what

## Description
![Image](https://user-images.githubusercontent.com/123933016/227610904-69ac165b-321b-4c62-9aa7-69528b4cdc82.png)

## Acceptance Criteria: 

- [x] there is a drop down menu on the board
- [x] the options will be the people you added in "new trip" and yourself
- [x] there is a section for each friend
- [x] to-do will show up in the section of the chosen friend

## Tasks:
- [x] create a drop down menu
- [x] link the data (friends array) from "new trip" to display is in the drop down menu
- [x] map over the friends array and create a section for each friend
